In [21]:
#Importando o pandas
import pandas as pd

In [22]:
#Importando a base de dados tradada
base = pd.read_excel('ChavesClientesTratada.xlsx')
base.head()

ID ChaveSituacao ClassRisco   CatCliente  Pagamento  Idade Genero  \
0   1          32FC     Ccinza  Basic-Alpha          1     32      F   
1   2          25MV   AAmarelo        Black          1     25      M   
2   3          27MV  B-Amarelo   Basic-Beta          1     27      M   
3   4          26FD   BAmarelo        Black          0     26      F   
4   5          26FD  C-Amarelo        Black          0     26      F   

  EstadoCivil Categoria CatVIP Risco  
0           C     Basic  Alpha     C  
1           V     Black  Comum     A  
2           V     Basic   Beta    B-  
3           D     Black  Comum     B  
4           D     Black  Comum    C-

In [23]:
# Removendo as colunas descenessárias
base = base.drop(['ID','ChaveSituacao','ClassRisco','CatCliente'],axis=1)
base.head()

Pagamento  Idade Genero EstadoCivil Categoria CatVIP Risco
0          1     32      F           C     Basic  Alpha     C
1          1     25      M           V     Black  Comum     A
2          1     27      M           V     Basic   Beta    B-
3          0     26      F           D     Black  Comum     B
4          0     26      F           D     Black  Comum    C-

In [24]:
# Importando o OneHotEnconder e transformando as colunas Genero e EstadoCivil em números
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
ohe_transform = ohe.fit_transform(base[['Genero', 'EstadoCivil']])

In [25]:
ohe.get_feature_names_out()

array(['Genero_F', 'Genero_M', 'EstadoCivil_C', 'EstadoCivil_D',
       'EstadoCivil_S', 'EstadoCivil_V'], dtype=object)

In [26]:
ohe_transform.toarray()

array([[1., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1.]])

In [27]:
# Criando um dataframe com os dados
df_ohe = pd.DataFrame(ohe_transform.toarray(), columns=ohe.get_feature_names_out())
df_ohe.head()

Genero_F  Genero_M  EstadoCivil_C  EstadoCivil_D  EstadoCivil_S  \
0       1.0       0.0            1.0            0.0            0.0   
1       0.0       1.0            0.0            0.0            0.0   
2       0.0       1.0            0.0            0.0            0.0   
3       1.0       0.0            0.0            1.0            0.0   
4       1.0       0.0            0.0            1.0            0.0   

   EstadoCivil_V  
0            0.0  
1            1.0  
2            1.0  
3            0.0  
4            0.0

In [28]:
# Incluindo o dataframe da base tradada
base = pd.concat([base, df_ohe], axis=1)
base.head()

Pagamento  Idade Genero EstadoCivil Categoria CatVIP Risco  Genero_F  \
0          1     32      F           C     Basic  Alpha     C       1.0   
1          1     25      M           V     Black  Comum     A       0.0   
2          1     27      M           V     Basic   Beta    B-       0.0   
3          0     26      F           D     Black  Comum     B       1.0   
4          0     26      F           D     Black  Comum    C-       1.0   

   Genero_M  EstadoCivil_C  EstadoCivil_D  EstadoCivil_S  EstadoCivil_V  
0       0.0            1.0            0.0            0.0            0.0  
1       1.0            0.0            0.0            0.0            1.0  
2       1.0            0.0            0.0            0.0            1.0  
3       0.0            0.0            1.0            0.0            0.0  
4       0.0            0.0            1.0            0.0            0.0

In [29]:
base.Categoria.values.reshape(-1,1)

array([['Basic'],
       ['Black'],
       ['Basic'],
       ['Black'],
       ['Black'],
       ['Platinum'],
       ['Platinum'],
       ['Basic'],
       ['Black'],
       ['Platinum'],
       ['Basic'],
       ['Basic'],
       ['Basic'],
       ['Platinum'],
       ['Black'],
       ['Platinum'],
       ['Black'],
       ['Black'],
       ['Platinum'],
       ['Platinum']], dtype=object)

In [30]:
# Importando o OrdinalEnconder e transformando a coluna Categoria em números
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()
oe_transform = oe.fit_transform(base.Categoria.values.reshape(-1,1))

In [32]:
oe_transform

array([[0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [2.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [0.],
       [0.],
       [2.],
       [1.],
       [2.],
       [1.],
       [1.],
       [2.],
       [2.]])

In [33]:
# Incluindo os dados na base
base['NrCategoria'] = oe_transform
base.head()

Pagamento  Idade Genero EstadoCivil Categoria CatVIP Risco  Genero_F  \
0          1     32      F           C     Basic  Alpha     C       1.0   
1          1     25      M           V     Black  Comum     A       0.0   
2          1     27      M           V     Basic   Beta    B-       0.0   
3          0     26      F           D     Black  Comum     B       1.0   
4          0     26      F           D     Black  Comum    C-       1.0   

   Genero_M  EstadoCivil_C  EstadoCivil_D  EstadoCivil_S  EstadoCivil_V  \
0       0.0            1.0            0.0            0.0            0.0   
1       1.0            0.0            0.0            0.0            1.0   
2       1.0            0.0            0.0            0.0            1.0   
3       0.0            0.0            1.0            0.0            0.0   
4       0.0            0.0            1.0            0.0            0.0   

   NrCategoria  
0          0.0  
1          1.0  
2          0.0  
3          1.0  
4          1.0

In [36]:
# Transformando a coluna Risco
oe = OrdinalEncoder(categories=[['C-','C','C+','B-','B','B+','A-','A','A+',]])
oe_transform_risco = oe.fit_transform(base.Risco.values.reshape(-1,1))
oe_transform_risco

array([[1.],
       [7.],
       [3.],
       [4.],
       [0.],
       [0.],
       [6.],
       [0.],
       [6.],
       [2.],
       [7.],
       [0.],
       [4.],
       [6.],
       [1.],
       [3.],
       [6.],
       [0.],
       [1.],
       [7.]])

In [38]:
# Incluindo a coluna transformada na base
base['NrRisco'] = oe_transform_risco
base.head()

Pagamento  Idade Genero EstadoCivil Categoria CatVIP Risco  Genero_F  \
0          1     32      F           C     Basic  Alpha     C       1.0   
1          1     25      M           V     Black  Comum     A       0.0   
2          1     27      M           V     Basic   Beta    B-       0.0   
3          0     26      F           D     Black  Comum     B       1.0   
4          0     26      F           D     Black  Comum    C-       1.0   

   Genero_M  EstadoCivil_C  EstadoCivil_D  EstadoCivil_S  EstadoCivil_V  \
0       0.0            1.0            0.0            0.0            0.0   
1       1.0            0.0            0.0            0.0            1.0   
2       1.0            0.0            0.0            0.0            1.0   
3       0.0            0.0            1.0            0.0            0.0   
4       0.0            0.0            1.0            0.0            0.0   

   NrCategoria  NrRisco  
0          0.0      1.0  
1          1.0      7.0  
2          0.0      3.0  
3          1.0      4.0  
4          1.0      0.0

In [39]:
# Definindo uma função com dados da coluna CatVIP
def define_VIP(valor):
    if valor == 'Alpha' or valor == 'Beta':
        return 1
    else:
        return 0

In [40]:
# Incluindo a coluna na base
base['NrVIP'] = base.CatVIP.apply(define_VIP)
base.head()

Pagamento  Idade Genero EstadoCivil Categoria CatVIP Risco  Genero_F  \
0          1     32      F           C     Basic  Alpha     C       1.0   
1          1     25      M           V     Black  Comum     A       0.0   
2          1     27      M           V     Basic   Beta    B-       0.0   
3          0     26      F           D     Black  Comum     B       1.0   
4          0     26      F           D     Black  Comum    C-       1.0   

   Genero_M  EstadoCivil_C  EstadoCivil_D  EstadoCivil_S  EstadoCivil_V  \
0       0.0            1.0            0.0            0.0            0.0   
1       1.0            0.0            0.0            0.0            1.0   
2       1.0            0.0            0.0            0.0            1.0   
3       0.0            0.0            1.0            0.0            0.0   
4       0.0            0.0            1.0            0.0            0.0   

   NrCategoria  NrRisco  NrVIP  
0          0.0      1.0      1  
1          1.0      7.0      0  
2          0.0      3.0      1  
3          1.0      4.0      0  
4          1.0      0.0      0

In [42]:
# Removendo as colunas descenessárias
base = base.drop(['Genero','EstadoCivil','Categoria','Risco','CatVIP'],axis=1)
base.head()

Pagamento  Idade  Genero_F  Genero_M  EstadoCivil_C  EstadoCivil_D  \
0          1     32       1.0       0.0            1.0            0.0   
1          1     25       0.0       1.0            0.0            0.0   
2          1     27       0.0       1.0            0.0            0.0   
3          0     26       1.0       0.0            0.0            1.0   
4          0     26       1.0       0.0            0.0            1.0   

   EstadoCivil_S  EstadoCivil_V  NrCategoria  NrRisco  NrVIP  
0            0.0            0.0          0.0      1.0      1  
1            0.0            1.0          1.0      7.0      0  
2            0.0            1.0          0.0      3.0      1  
3            0.0            0.0          1.0      4.0      0  
4            0.0            0.0          1.0      0.0      0

In [43]:
X = base.drop('Pagamento',axis=1)
y = base.Pagamento

from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X,y)

reg.score(X,y)

0.6197521275369209