In [ ]:
import numpy as np

In [ ]:
# Criando uma array
a = np.array([[1,2,3,4,5,6],[3,4,5,6,7,8,]])
print(a)
print(type(a))

[[1 2 3 4 5 6]
 [3 4 5 6 7 8]]
<class 'numpy.ndarray'>


In [ ]:
zero_array = np.zeros(shape = (5,3,6))
print(zero_array)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [ ]:
um_array = np.ones((2,3))
print(um_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
vazio = np.empty((3,4))
print(vazio)

[[1.52681693e-315 0.00000000e+000 1.46921981e+195 2.87908278e+214]
 [1.28036948e-152 5.04443784e+180 1.81363726e-152 1.12044254e+219]
 [1.69593624e-152 1.44574571e-308 2.59903841e-144 6.73616716e-310]]


In [ ]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr = np.arange(step=30, start=50, stop=200)
print(arr)

[ 50  80 110 140 170]


In [ ]:
array_linear = np.linspace(0, 100, num = 20, endpoint= False)
print(array_linear)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55. 60. 65. 70. 75. 80. 85.
 90. 95.]


In [ ]:
array_linear = np.linspace(0, 100, num = 20, retstep= False)
print(array_linear)

[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]


In [ ]:
print(zero_array.shape)
print(zero_array.size)
print(zero_array.ndim)

(5, 3, 6)
90
3
